# Generated by Django 4.1.7 on 2023-03-15 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='specification',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='product',
            name='warranty',
            field=models.CharField(max_length=15, verbose_name='Гарантия'),
        ),
    ]
