# Generated by Django 4.1.7 on 2023-03-17 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spec_gadget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CPU', models.CharField(max_length=50, verbose_name='Имя')),
                ('frequency', models.FloatField()),
                ('memory', models.IntegerField()),
                ('size', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='spec_gadget',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.spec_gadget'),
        ),
    ]
