# Generated by Django 4.1.7 on 2023-03-17 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_spec_gadget_product_spec_gadget'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spec_gadget',
            old_name='CPU',
            new_name='cpu',
        ),
    ]
